import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, access, rm, symlink, rename } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { createTestDatabase } from "../../../../scripts/test-db.mjs";
import { getStorageCatalog, deleteStorageVideos } from "./storage-videos.ts";
import { adaptClient } from "./db.ts";
import pg from "pg";
import { SCENE_KIND_BY_KEY, STANDARD_SCENE_KEYS, videoDocumentSchema } from "@content-gen/domain/video";

const testDb = await createTestDatabase();
const root = await mkdtemp(join(tmpdir(), "storage-delete-test-"));
const client = new pg.Client({ connectionString: testDb.url });
await client.connect();
const db = adaptClient(client);
const now = new Date().toISOString();
const campaignId = randomUUID();
const itemId = randomUUID();
const document = videoDocumentSchema.parse({ schemaVersion: 1, slug: "storage-test", title: "Video conservado", width: 1080, height: 1920, fps: 30, templateId: "standard", scenes: STANDARD_SCENE_KEYS.map(id => ({ id, kind: SCENE_KIND_BY_KEY[id], durationFrames: 90, content: { title: "Prueba", voiceover: "Narración conservada" } })) });
const content = { id: itemId, schemaVersion: 1, campaignId, type: "video", revision: 0, createdAt: now, updatedAt: now, archivedAt: null, document: { schemaVersion: 1, data: document } };
async function seed(hash: string, copies = 1) {
  const key = `assets/${hash.repeat(64)}.mp4`;
  await writeFile(join(root, "media", key), Buffer.alloc(8192, hash));
  const ids: string[] = [];
  for (let i = 0; i < copies; i++) {
    const id = randomUUID(); ids.push(id);
    const asset = { id, schemaVersion: 1, filename: `final-${hash}.mp4`, storageKey: key, mimeType: "video/mp4", sizeBytes: 8192, contentItemId: itemId, campaignId, createdAt: now };
    await client.query("INSERT INTO assets VALUES ($1,1,$2,$3)", [id, JSON.stringify(asset), now]);
    const jobId = randomUUID();
    const job = { id: jobId, schemaVersion: 1, contentItemId: itemId, compositionId: "StandardVideo", inputProps: { document }, status: "completed", progress: 100, outputAssetId: id, createdAt: now, completedAt: now, error: null, log: [] };
    await client.query("INSERT INTO render_jobs VALUES ($1,1,$2,$3,$4)", [jobId, itemId, JSON.stringify(job), now]);
    const exportId = randomUUID();
    await client.query("INSERT INTO exports VALUES ($1,1,$2,$3,$4,$5)", [exportId, itemId, id, JSON.stringify({ id: exportId, contentItemId: itemId, format: "mp4", assetId: id }), now]);
  }
  return { key: `media/${key}`, ids };
}
try {
  await mkdir(join(root, "media/assets"), { recursive: true });
  await client.query("INSERT INTO campaigns VALUES ($1,1,NULL,$2,$3,$3,NULL)", [campaignId, JSON.stringify({ id: campaignId, name: "Prueba" }), now]);
  await client.query("INSERT INTO content_items VALUES ($1,1,$2,'video',$3,0,$4,$4,NULL)", [itemId, campaignId, JSON.stringify(content), now]);
  const a = await seed("a", 2);
  const b = await seed("b");
  await writeFile(join(root, "media/assets/photo.webp"), "image");
  const catalog = await getStorageCatalog(root, db);
  const selected = catalog.files.filter(f => [a.key, b.key].includes(f.key));
  assert.equal(selected.length, 2, "una fila por archivo físico, no por exportación");
  assert.equal(selected.find(f => f.key === a.key)?.exportCount, 2);
  assert.ok(selected.every(f => f.deletable));
  assert.equal(catalog.files.find(f => f.name === "photo.webp")?.deletable, false);
  const expected = selected.reduce((sum, f) => sum + f.allocatedBytes, 0);
  const result = await deleteStorageVideos(root, selected.map(({ key, version }) => ({ key, version })), db);
  assert.equal(result.deleted, 2);
  assert.equal(result.estimatedFreedBytes, expected);
  await assert.rejects(access(join(root, a.key)));
  await assert.rejects(access(join(root, b.key)));
  assert.equal((await client.query("SELECT count(*) FROM exports")).rows[0].count, 0);
  assert.equal((await client.query("SELECT count(*) FROM assets")).rows[0].count, 0);
  const preserved = (await client.query("SELECT document_json FROM content_items WHERE id=$1", [itemId])).rows[0].document_json;
  assert.deepEqual(JSON.parse(preserved), content, "proyecto y guion no se modifican");
  assert.ok((await client.query("SELECT data_json FROM render_jobs")).rows.every(row => JSON.parse(row.data_json).outputAssetId === null));
  const deletedJob = JSON.parse((await client.query("SELECT data_json FROM render_jobs LIMIT 1")).rows[0].data_json);
  assert.equal(deletedJob.status, "failed", "se puede reintentar/renderizar de nuevo");
  assert.deepEqual(deletedJob.inputProps.document, document);
  const c = await seed("c");
  await mkdir(join(root, ".storage-trash"), { recursive: true });
  const cName = c.key.split("/").at(-1)!;
  await writeFile(join(root, ".storage-trash", cName.replace(".mp4", ".json")), JSON.stringify({ assetIds: c.ids }));
  await rename(join(root, c.key), join(root, ".storage-trash", cName));
  await getStorageCatalog(root, db);
  await access(join(root, c.key));
  await assert.rejects(access(join(root, ".storage-trash", cName)), /ENOENT/);
  let rows = (await getStorageCatalog(root, db)).files;
  const old = rows.find(f => f.key === c.key)!;
  await writeFile(join(root, c.key), "changed");
  await assert.rejects(deleteStorageVideos(root, [{ key: c.key, version: old.version }], db), /cambió/);
  assert.equal(await readFile(join(root, c.key), "utf8"), "changed");
  await assert.rejects(deleteStorageVideos(root, [{ key: "../../escape.mp4", version: "x" }], db), /selección|válida/);
  await client.query("UPDATE content_items SET document_json=$1 WHERE id=$2", [JSON.stringify({ ...content, custom: { url: `/api/assets/${c.ids[0]}` } }), itemId]);
  rows = (await getStorageCatalog(root, db)).files;
  const protectedFile = rows.find(f => f.key === c.key)!;
  assert.equal(protectedFile.deletable, false);
  await assert.rejects(deleteStorageVideos(root, [{ key: c.key, version: protectedFile.version }], db), /protegido|utiliza/);
  await client.query("UPDATE content_items SET document_json=$1 WHERE id=$2", [JSON.stringify(content), itemId]);
  await rm(join(root, c.key));
  await symlink(join(root, "media/assets/photo.webp"), join(root, c.key));
  await assert.rejects(deleteStorageVideos(root, [{ key: c.key, version: old.version }], db), /cambió|existe|protegido/);
  assert.equal(await readFile(join(root, "media/assets/photo.webp"), "utf8"), "image");
  console.log("Postgres + archivos reales: borrado múltiple, deduplicación, exportaciones limpiadas, proyecto conservado, re-render, cambios, referencias y traversal verificados.");
} finally { await client.end(); await testDb.drop(); await rm(root, { recursive: true, force: true }); }
