import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL, URL } from "node:url";
import console from "node:console";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
const source = fileURLToPath(new URL("../src/", import.meta.url));
registerHooks({
 resolve(s,c,next){if(s==="@/components/app-sidebar")return {url:"fixture:sidebar",shortCircuit:true};if(s==="next/link")return next("next/link.js",c);if(s.startsWith("@/")){const p=`${source}${s.slice(2)}`;for(const e of ["", ".tsx", ".ts"]){try{readFileSync(p+e);return next(pathToFileURL(p+e).href,c);}catch{/* Siguiente extensión. */}}}if(s.startsWith(".")&&!/\.[a-z]+$/.test(s)){for(const e of [".tsx",".ts"]){try{return next(s+e,c);}catch{/* Siguiente extensión. */}}}return next(s,c);},
 load(url,c,next){if(url==="fixture:sidebar")return {format:"module",shortCircuit:true,source:"export const AppSidebar=()=>null;"};if(/\.(tsx|ts)$/.test(url))return {format:"module",shortCircuit:true,source:ts.transpileModule(readFileSync(fileURLToPath(url),"utf8"),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText};return next(url,c);}
});
const { BudgetPanel } = await import("../src/components/automations/budget-panel.tsx");
const data={settings:{timezone:"America/Bogota",limits:{day:2,week:10,month:30},blockAutomations:true},currency:"USD",periods:Object.fromEntries(["day","week","month"].map(p=>[p,{limit:p==="day"?2:10,used:3,remaining:p==="day"?-1:7,unknown:1,from:"2026-10-06T05:00:00Z",to:"2026-10-07T05:00:00Z"}]))};
const html=renderToStaticMarkup(React.createElement(BudgetPanel,{initialData:data}));
assert.ok(html.includes("Diario")&&html.includes("Semanal")&&html.includes("Mensual"));
assert.ok(html.includes("America/Bogota"));
assert.ok(html.includes("Costo incompleto"));
assert.ok(html.includes("Superado"));
assert.ok(html.includes("Guardar presupuesto"));
assert.ok(html.includes("llamadas en curso"),"explica que no es un techo exacto de facturación");
console.log("Budget UI: períodos, zona, exceso, costos desconocidos y alcance del freno renderizados.");
const { buildAutomationFlow } = await import("../src/components/automations/flow-model.ts");
const execution={id:"run",automationId:"a",kind:"radar",status:"completed",startedAt:"2026-10-06T12:00:00Z",completedAt:"2026-10-06T12:01:00Z",durationMs:60000,error:null,amount:0.12,unknown:0,result:{summary:{kept:3,found:5}},operations:[{id:"g",operation:"radar-research",provider:"openai",model:"fixture-model",status:"completed",amount:0.12}]};
const flow=buildAutomationFlow({id:"a",kind:"radar",name:"IA",active:true,frequency:"week",time:"12:00",scan:{verticals:["IA"],focus:"Agentes"}},execution,data);
assert.equal(flow.nodes.length,5);
assert.equal(flow.edges.length,4);
assert.ok(flow.nodes.some(n=>n.data.title==="Presupuesto"));
assert.ok(flow.nodes.some(n=>n.data.detail.includes("3 temas guardados")));
assert.ok(flow.nodes.some(n=>n.data.detail.includes("Agentes")));
const blocked=buildAutomationFlow({id:"a",kind:"carousel",name:"Carruseles",active:true,topics:["Tema uno"],usedTopics:[],kindLabel:"Editable",slides:6,ruleLabel:"Lunes 19:00"},{...execution,status:"blocked",kind:"carousel",error:"Presupuesto agotado",result:{},operations:[]},data);
assert.equal(blocked.nodes.find(n=>n.id==="budget").data.state,"blocked");
assert.equal(blocked.nodes.find(n=>n.id==="output").data.state,"pending");
console.log("Flow model: radar/carrusel, presupuesto y resultado real sin pasos ficticios verificados.");
const { RadarAutomationForm } = await import("../src/components/automations/radar-automation-form.tsx");
const { Sheet } = await import("../src/components/ui/sheet.tsx");
const radarForm=renderToStaticMarkup(React.createElement(Sheet,null,React.createElement(RadarAutomationForm,{editing:null,verticals:["IA","Seguridad"],onSubmit:async()=>{},onCancel:()=>{}})));
assert.ok(radarForm.includes("UTC"));
assert.ok(radarForm.includes("Activar búsqueda automática"));
assert.ok(!/checked=""[^>]*\/>Activar búsqueda automática/.test(radarForm),"nueva regla pausada por defecto");
assert.ok(radarForm.includes("Consume créditos"));
const { ExecutionDetails } = await import("../src/components/automations/execution-details.tsx");
const details=renderToStaticMarkup(React.createElement(ExecutionDetails,{execution:{...execution,unknown:1},onSelect:()=>{}}));
assert.ok(details.includes("fixture-model"));
assert.ok(details.includes("3 guardados"));
assert.ok(details.includes("Costo incompleto"));
assert.ok(details.includes("radar-research"));
console.log("Automation UI: radar pausado, advertencia de cobro y operaciones reales renderizados.");
const { default: AutomationsPage } = await import("../src/app/automations/page.tsx");
const page=renderToStaticMarkup(React.createElement(AutomationsPage));
assert.ok(page.includes("Buscar automatizaciones"));
assert.ok(page.includes("Automatizar radar"));
assert.ok(page.includes("Presupuesto"));
assert.ok(page.includes("h-dvh")&&page.includes("overflow-hidden"),"shell limitado al viewport");
console.log("Automation workspace: navegación, creación y scroll interno renderizados.");
