import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import console from "node:console";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
registerHooks({ load(url, context, next) {
  if (url.endsWith(".tsx")) return { format: "module", shortCircuit: true, source: ts.transpileModule(readFileSync(fileURLToPath(url), "utf8"), { compilerOptions: { jsx: ts.JsxEmit.ReactJSX, module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText };
  return next(url, context);
} });
const { JevRadarReview } = await import("../src/components/radar/jev-review.tsx");
const render = observation => renderToStaticMarkup(React.createElement(JevRadarReview, { observation }));
assert.equal(render(null), "", "si está apagado no añade ruido visual");
const observation = { mode: "observe", model: "jev-1.13.0", status: "completed", error: null, omitted: 2, comparedTitles: 30, decisions: [{ topicId: "t1", title: "Automatización para clínicas", relevance: 0.95, duplicate: 0.9, recommendation: "duplicate" }, { topicId: "t2", title: "Novedad relevante", relevance: 0.95, duplicate: 0.1, recommendation: "keep" }] };
const html = render(observation);
assert.ok(html.includes("<details"), "recomendaciones plegadas, no otro panel grande");
assert.ok(!html.includes("<details open"));
assert.ok(html.includes("Posible repetido"));
assert.ok(html.includes("No se descartó ni modificó ningún tema"));
assert.ok(html.includes("30 títulos recientes"));
assert.ok(html.includes("2 temas sin evaluar"));
assert.ok(html.includes("Automatización para clínicas"));
const failed = render({ ...observation, status: "failed", decisions: [], error: "Falta TYPESAFE_API_KEY; no se llamó a JEV." });
assert.ok(failed.includes("El Radar continuó normalmente"));
assert.ok(failed.includes("TYPESAFE_API_KEY"));
assert.ok(!failed.includes("evaluados"), "no anuncia evaluación exitosa si falló");
console.log("JEV UI: recomendaciones plegadas, cobertura parcial, error y modo apagado renderizados.");
